In [1]:
# ============================================================
# Celda 1: Importación de librerías y configuración inicial
# ============================================================
# En esta celda se importan las librerías necesarias para la limpieza
# y preparación del dataset. También se define la ruta del archivo original,
# la variable objetivo y la paleta visual base.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

DATASET_PATH = "dataset-phishing.csv"
TARGET_COL = "status"

COLOR_PRIMARIO = "#3A6EA5"
COLOR_SECUNDARIO = "#5DADE2"
COLOR_TERCIARIO = "#95A5A6"

sns.set_theme(style="whitegrid")

In [2]:
# ============================================================
# Celda 2: Carga del dataset original
# ============================================================
# En esta celda se carga el dataset original y se genera una copia de trabajo.
# Esto permite mantener intacto el archivo base durante todo el proceso.

df_original = pd.read_csv(DATASET_PATH)

df_clean = df_original.copy()

print("Shape original:", df_original.shape)
print("Shape copia de trabajo:", df_clean.shape)

display(df_clean.head())

Shape original: (11430, 89)
Shape copia de trabajo: (11430, 89)

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www,nb_com,nb_dslash,http_in_path,https_token,ratio_digits_url,ratio_digits_host,punycode,port,tld_in_path,tld_in_subdomain,abnormal_subdomain,nb_subdomains,prefix_suffix,random_domain,shortening_service,path_extension,nb_redirection,nb_external_redirection,length_words_raw,char_repeat,shortest_words_raw,shortest_word_host,shortest_word_path,longest_words_raw,longest_word_host,longest_word_path,avg_words_raw,avg_word_host,avg_word_path,phish_hints,domain_in_brand,brand_in_subdomain,brand_in_path,suspecious_tld,statistical_report,nb_hyperlinks,ratio_intHyperlinks,ratio_extHyperlinks,ratio_nullHyperlinks,nb_extCSS,ratio_intRedirection,ratio_extRedirection,ratio_intErrors,ratio_extErrors,login_form,external_favicon,links_in_tags,submit_email,ratio_intMedia,ratio_extMedia,sfh,iframe,popup_window,safe_anchor,onmouseover,right_clic,empty_title,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,status
0,http://www.crestonwood.com/router.php,37,19,0,3,0,0,0,0,0,0,0,0,0,3,0,1,0,0,0,0,1,0,0,0,1,0.000000,0.0,0,0,0,0,0,3,0,0,0,0,0,0,4,4,3,3,3,11,11,6,5.750000,7.0,4.500000,0,0,0,0,0,0,17,0.529412,0.470588,0,0,0,0.875000,0,0.500000,0,0,80.000000,0,100.000000,0.000000,0,0,0,0.0,0,0,0,0,1,0,45,-1,0,1,1,4,legitimate
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,1,0,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0,0,0,0,0,1,0.220779,0.0,0,0,0,0,0,1,0,0,0,0,1,0,4,4,2,19,2,32,19,32,15.750000,19.0,14.666667,0,0,0,0,0,0,30,0.966667,0.033333,0,0,0,0.000000,0,0.000000,0,0,100.000000,0,80.000000,20.000000,0,0,0,100.0,0,0,0,1,0,0,77,5767,0,0,1,2,phishing
2,https://support-appleld.com.secureupdate.duila...,126,50,1,4,1,0,1,2,0,3,2,0,0,5,0,1,0,0,0,0,0,1,0,0,0,0.150794,0.0,0,0,0,1,0,3,1,0,0,0,1,0,12,2,2,3,2,17,13,17,8.250000,8.4,8.142857,0,0,0,0,0,0,4,1.000000,0.000000,0,0,0,0.000000,0,0.000000,0,0,100.000000,0,0.000000,0.000000,0,0,0,100.0,0,0,0,1,0,0,14,4004,5828815,0,1,0,phishing
3,http://rgipt.ac.in,18,11,0,2,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,1,0.000000,0.0,0,0,0,0,0,2,0,0,0,0,1,0,1,0,5,5,0,5,5,0,5.000000,5.0,0.000000,0,0,0,0,0,0,149,0.973154,0.026846,0,0,0,0.250000,0,0.250000,0,0,100.000000,0,96.428571,3.571429,0,0,0,62.5,0,0,0,1,0,0,62,-1,107721,0,0,3,legitimate
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,0,2,2,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0,1,0,0,0,1,0.000000,0.0,0,0,0,0,0,2,0,0,0,0,1,0,6,3,3,3,4,11,7,11,6.333333,5.0,7.000000,0,0,0,0,0,0,102,0.470588,0.529412,0,0,0,0.537037,0,0.018519,1,0,76.470588,0,0.000000,100.000000,0,0,0,0.0,0,0,0,0,1,0,224,8175,8725,0,0,6,legitimate

In [3]:
# ============================================================
# Celda 3: Conversión de la variable objetivo a formato binario
# ============================================================
# En esta celda se convierte la variable objetivo a formato binario,
# donde:
# 0 = legítima
# 1 = phishing
#
# El dataset ya contiene únicamente las clases 'legitimate' y 'phishing',
# por lo que se realiza un mapeo directo.

df_clean[TARGET_COL] = (
    df_clean[TARGET_COL]
    .astype(str)
    .str.lower()
    .str.strip()
)

df_clean[TARGET_COL] = df_clean[TARGET_COL].map({
    "legitimate": 0,
    "phishing": 1
})

df_clean = df_clean.dropna(subset=[TARGET_COL])

df_clean[TARGET_COL] = df_clean[TARGET_COL].astype(int)

print("Valores únicos del target:")
print(df_clean[TARGET_COL].unique())

print("\nDistribución de clases:")
display(df_clean[TARGET_COL].value_counts())

print("\nShape después de transformar target:")
print(df_clean.shape)

Valores únicos del target:
[0 1]

Distribución de clases:

status
0    5715
1    5715
Name: count, dtype: int64

Shape después de transformar target:
(11430, 89)

In [4]:
# ============================================================
# Celda 4: Eliminación de URLs duplicadas
# ============================================================
# En esta celda se eliminan registros con URLs repetidas, conservando
# la primera aparición. Esto evita que una misma URL aparezca más de una vez
# durante el entrenamiento o evaluación del modelo.

duplicadas_url = df_clean["url"].duplicated().sum()

print("URLs duplicadas antes de limpiar:", duplicadas_url)

if duplicadas_url > 0:
    urls_duplicadas = df_clean[df_clean["url"].duplicated(keep=False)].sort_values("url")
    print("\nRegistros duplicados detectados:")
    display(urls_duplicadas)

df_clean = df_clean.drop_duplicates(subset=["url"], keep="first")

print("\nURLs duplicadas después de limpiar:", df_clean["url"].duplicated().sum())
print("Shape después de eliminar URLs duplicadas:", df_clean.shape)

URLs duplicadas antes de limpiar: 1

Registros duplicados detectados:

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www,nb_com,nb_dslash,http_in_path,https_token,ratio_digits_url,ratio_digits_host,punycode,port,tld_in_path,tld_in_subdomain,abnormal_subdomain,nb_subdomains,prefix_suffix,random_domain,shortening_service,path_extension,nb_redirection,nb_external_redirection,length_words_raw,char_repeat,shortest_words_raw,shortest_word_host,shortest_word_path,longest_words_raw,longest_word_host,longest_word_path,avg_words_raw,avg_word_host,avg_word_path,phish_hints,domain_in_brand,brand_in_subdomain,brand_in_path,suspecious_tld,statistical_report,nb_hyperlinks,ratio_intHyperlinks,ratio_extHyperlinks,ratio_nullHyperlinks,nb_extCSS,ratio_intRedirection,ratio_extRedirection,ratio_intErrors,ratio_extErrors,login_form,external_favicon,links_in_tags,submit_email,ratio_intMedia,ratio_extMedia,sfh,iframe,popup_window,safe_anchor,onmouseover,right_clic,empty_title,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,status
6035,http://e710z0ear.du.r.appspot.com/c:/users/use...,62,26,0,4,0,0,0,0,0,0,0,0,0,6,0,2,0,0,0,0,0,0,0,0,1,0.064516,0.153846,0,0,0,0,0,3,0,0,1,0,0,0,8,2,1,1,1,14,9,14,5.375,4.75,6.0,0,0,0,0,0,0,21,0.190476,0.809524,0,1,0,0.294118,0,0.0,0,1,0.0,0,20.0,80.0,0,0,0,25.0,0,0,0,1,1,0,217,5627,0,0,1,5,1
11305,http://e710z0ear.du.r.appspot.com/c:/users/use...,54,26,0,4,0,0,0,0,0,0,0,0,0,6,0,2,0,0,0,0,0,0,0,0,1,0.074074,0.153846,0,0,0,0,0,3,0,0,1,0,0,0,8,1,1,1,1,9,9,6,4.375,4.75,4.0,0,0,0,0,0,0,21,0.190476,0.809524,0,1,0,0.176471,0,0.0,0,1,0.0,0,20.0,80.0,0,0,0,25.0,0,0,0,1,1,0,230,5614,0,0,1,5,1

URLs duplicadas después de limpiar: 0
Shape después de eliminar URLs duplicadas: (11429, 89)

In [5]:
# ============================================================
# Celda 5: Eliminación de filas duplicadas completas
# ============================================================
# En esta celda se eliminan filas completamente duplicadas.
# Aunque en el EDA no se observaron duplicados completos, se mantiene
# esta validación para asegurar consistencia en el pipeline.

duplicadas_filas = df_clean.duplicated().sum()

print("Filas duplicadas completas antes de limpiar:", duplicadas_filas)

df_clean = df_clean.drop_duplicates(keep="first")

print("Filas duplicadas completas después de limpiar:", df_clean.duplicated().sum())
print("Shape después de eliminar filas duplicadas:", df_clean.shape)

Filas duplicadas completas antes de limpiar: 0
Filas duplicadas completas después de limpiar: 0
Shape después de eliminar filas duplicadas: (11429, 89)

In [6]:
# ============================================================
# Celda 6: Identificación y eliminación de variables constantes
# ============================================================
# En esta celda se detectan variables que poseen un único valor en todo
# el dataset. Estas variables no aportan información predictiva y pueden
# eliminarse antes del entrenamiento.

unique_counts = df_clean.nunique()

constant_features = unique_counts[unique_counts <= 1].index.tolist()

print("Variables constantes detectadas:")
print(constant_features)

print("\nCantidad de variables constantes:", len(constant_features))

df_clean = df_clean.drop(columns=constant_features)

print("\nShape después de eliminar variables constantes:", df_clean.shape)

Variables constantes detectadas:
['nb_or', 'ratio_nullHyperlinks', 'ratio_intRedirection', 'ratio_intErrors', 'submit_email', 'sfh']

Cantidad de variables constantes: 6

Shape después de eliminar variables constantes: (11429, 83)

In [7]:
# ============================================================
# Celda 7: Revisión y tratamiento de valores nulos
# ============================================================
# En esta celda se revisan valores nulos. Si existen, se imputan usando
# la mediana en variables numéricas. Esto evita errores posteriores
# durante el entrenamiento de modelos.

missing_before = df_clean.isnull().sum()
missing_before = missing_before[missing_before > 0].sort_values(ascending=False)

print("Valores nulos antes de imputar:")
display(missing_before)

numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col] = df_clean[col].fillna(df_clean[col].median())

missing_after = df_clean.isnull().sum()
missing_after = missing_after[missing_after > 0].sort_values(ascending=False)

print("\nValores nulos después de imputar:")
display(missing_after)

if missing_after.empty:
    print("No quedan valores nulos en el dataset.")

Valores nulos antes de imputar:

Series([], dtype: int64)

Valores nulos después de imputar:

Series([], dtype: int64)

No quedan valores nulos en el dataset.

In [8]:
# ============================================================
# Celda 8: Revisión de valores infinitos
# ============================================================
# En esta celda se reemplazan posibles valores infinitos por NaN
# y luego se imputan con la mediana de cada variable numérica.

numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns

inf_count = np.isinf(df_clean[numeric_cols]).sum()
inf_count = inf_count[inf_count > 0]

print("Valores infinitos detectados:")
display(inf_count)

df_clean[numeric_cols] = df_clean[numeric_cols].replace([np.inf, -np.inf], np.nan)

for col in numeric_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col] = df_clean[col].fillna(df_clean[col].median())

print("Valores infinitos tratados correctamente.")

Valores infinitos detectados:

Series([], dtype: int64)

Valores infinitos tratados correctamente.

In [9]:
# ============================================================
# Celda 9: Revisión de valores negativos especiales
# ============================================================
# En esta celda se identifican variables numéricas que contienen
# valores negativos. En datasets de phishing, ciertos atributos
# asociados a consultas WHOIS pueden utilizar valores como -1
# para representar:
#
# - ausencia de información
# - fallos en la consulta
# - dominios ocultos o inválidos
#
# Debido a que estos valores pueden contener información relevante
# para la detección de phishing, no serán eliminados ni imputados
# en esta etapa.

numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns

negative_report = []

for col in numeric_cols:
    
    negative_count = (df_clean[col] < 0).sum()
    
    if negative_count > 0:
        
        negative_report.append({
            "feature": col,
            "negative_count": negative_count,
            "negative_percent": round(
                negative_count / len(df_clean) * 100,
                2
            ),
            "min_value": df_clean[col].min()
        })

negative_report_df = (
    pd.DataFrame(negative_report)
    .sort_values("negative_percent", ascending=False)
)

display(negative_report_df)

if negative_report_df.empty:
    print("No se encontraron valores negativos.")
else:
    print("""
Nota:
Los valores negativos detectados se conservarán temporalmente,
ya que podrían representar información relevante asociada
a consultas WHOIS fallidas o dominios sospechosos.
""")

                      feature  negative_count  negative_percent  min_value
1                  domain_age            1837             16.07        -12
0  domain_registration_length              46              0.40         -1

Nota:
Los valores negativos detectados se conservarán temporalmente,
ya que podrían representar información relevante asociada
a consultas WHOIS fallidas o dominios sospechosos.

In [10]:
# ============================================================
# Celda 10: Conversión segura de variables numéricas
# ============================================================
# En esta celda se asegura que todas las variables predictoras,
# excepto la URL, estén en formato numérico. Cualquier valor no convertible
# se transforma en NaN y se imputa con la mediana.

cols_no_predictoras = ["url", TARGET_COL]

feature_cols = [col for col in df_clean.columns if col not in cols_no_predictoras]

for col in feature_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

print("Tipos de datos después de conversión:")
display(df_clean.dtypes.value_counts())

print("\nShape actual:", df_clean.shape)

Tipos de datos después de conversión:

int64      68
float64    13
object      1
int32       1
Name: count, dtype: int64

Shape actual: (11429, 83)

In [11]:
# ============================================================
# Celda 11: Validación final del dataset limpio
# ============================================================
# En esta celda se realiza una validación final del dataset limpio:
# dimensiones, nulos, duplicados, tipos de datos y distribución de clases.

print("Shape final:", df_clean.shape)

print("\nValores nulos totales:", df_clean.isnull().sum().sum())

print("Filas duplicadas completas:", df_clean.duplicated().sum())

if "url" in df_clean.columns:
    print("URLs duplicadas:", df_clean["url"].duplicated().sum())

print("\nDistribución final del target:")
display(df_clean[TARGET_COL].value_counts())

print("\nTipos de datos:")
display(df_clean.dtypes.value_counts())

display(df_clean.head())

Shape final: (11429, 83)

Valores nulos totales: 0
Filas duplicadas completas: 0
URLs duplicadas: 0

Distribución final del target:

status
0    5715
1    5714
Name: count, dtype: int64

Tipos de datos:

int64      68
float64    13
object      1
int32       1
Name: count, dtype: int64

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_eq,nb_underscore,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www,nb_com,nb_dslash,http_in_path,https_token,ratio_digits_url,ratio_digits_host,punycode,port,tld_in_path,tld_in_subdomain,abnormal_subdomain,nb_subdomains,prefix_suffix,random_domain,shortening_service,path_extension,nb_redirection,nb_external_redirection,length_words_raw,char_repeat,shortest_words_raw,shortest_word_host,shortest_word_path,longest_words_raw,longest_word_host,longest_word_path,avg_words_raw,avg_word_host,avg_word_path,phish_hints,domain_in_brand,brand_in_subdomain,brand_in_path,suspecious_tld,statistical_report,nb_hyperlinks,ratio_intHyperlinks,ratio_extHyperlinks,nb_extCSS,ratio_extRedirection,ratio_extErrors,login_form,external_favicon,links_in_tags,ratio_intMedia,ratio_extMedia,iframe,popup_window,safe_anchor,onmouseover,right_clic,empty_title,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,status
0,http://www.crestonwood.com/router.php,37,19,0,3,0,0,0,0,0,0,0,0,3,0,1,0,0,0,0,1,0,0,0,1,0.000000,0.0,0,0,0,0,0,3,0,0,0,0,0,0,4,4,3,3,3,11,11,6,5.750000,7.0,4.500000,0,0,0,0,0,0,17,0.529412,0.470588,0,0.875000,0.500000,0,0,80.000000,100.000000,0.000000,0,0,0.0,0,0,0,0,1,0,45,-1,0,1,1,4,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,1,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0,0,0,0,0,1,0.220779,0.0,0,0,0,0,0,1,0,0,0,0,1,0,4,4,2,19,2,32,19,32,15.750000,19.0,14.666667,0,0,0,0,0,0,30,0.966667,0.033333,0,0.000000,0.000000,0,0,100.000000,80.000000,20.000000,0,0,100.0,0,0,0,1,0,0,77,5767,0,0,1,2,1
2,https://support-appleld.com.secureupdate.duila...,126,50,1,4,1,0,1,2,3,2,0,0,5,0,1,0,0,0,0,0,1,0,0,0,0.150794,0.0,0,0,0,1,0,3,1,0,0,0,1,0,12,2,2,3,2,17,13,17,8.250000,8.4,8.142857,0,0,0,0,0,0,4,1.000000,0.000000,0,0.000000,0.000000,0,0,100.000000,0.000000,0.000000,0,0,100.0,0,0,0,1,0,0,14,4004,5828815,0,1,0,1
3,http://rgipt.ac.in,18,11,0,2,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,1,0.000000,0.0,0,0,0,0,0,2,0,0,0,0,1,0,1,0,5,5,0,5,5,0,5.000000,5.0,0.000000,0,0,0,0,0,0,149,0.973154,0.026846,0,0.250000,0.250000,0,0,100.000000,96.428571,3.571429,0,0,62.5,0,0,0,1,0,0,62,-1,107721,0,0,3,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,0,2,2,0,0,0,0,0,0,0,5,0,1,0,0,0,0,1,0,0,0,1,0.000000,0.0,0,0,0,0,0,2,0,0,0,0,1,0,6,3,3,3,4,11,7,11,6.333333,5.0,7.000000,0,0,0,0,0,0,102,0.470588,0.529412,0,0.537037,0.018519,1,0,76.470588,0.000000,100.000000,0,0,0.0,0,0,0,0,1,0,224,8175,8725,0,0,6,0

In [12]:
# ============================================================
# Celda 12: Guardado del dataset limpio
# ============================================================
# En esta celda se guarda el dataset limpio generado durante la etapa
# de preparación. Este archivo será utilizado en el siguiente notebook
# para la selección de características.

OUTPUT_PATH = "dataset-phishing-clean.csv"

df_clean.to_csv(OUTPUT_PATH, index=False)

print("Dataset limpio guardado correctamente.")
print("Archivo:", OUTPUT_PATH)
print("Shape guardado:", df_clean.shape)

Dataset limpio guardado correctamente.
Archivo: dataset-phishing-clean.csv
Shape guardado: (11429, 83)